server:
  port: 8762
spring:
  application:
    name: lagou-cloud-eureka-service #应用名称=服务名称
eureka:
  instance:
      hostname: LagouCloudEurekaServerB #当前实例主机名
  client:
    service-url:  #客户端使用的 server地址
      defaultZone:  http://LagouCloudEurekaServerA:8761/eureka #默认server地址
    register-with-eureka: true # server和client是相同架构,server不需要向eureka注册
    fetch-registry: true #server不需要从注册中心拉去服务信息