spring:
  application:
    name: lagou-service-autodeliver
server:
  port: 28092
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
#lagou-service-resume:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
lagou-service-resume:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 6000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 0
    MaxAutoRetriedNextServer: 0
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RoundRobinRule
logging:
  level:
    com.lagou.edu.service.ResumeServiceFeignClient: debug
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000